# roles/conscience/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_conscience_namespace }}"
    - "{{ openio_conscience_sysconfig_dir }}/conscience-{{ openio_conscience_serviceid }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "conscience.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        conscience-{{ openio_conscience_serviceid }}/conscience-{{ openio_conscience_serviceid }}.conf"
    - src: "services.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        conscience-{{ openio_conscience_serviceid }}/conscience-{{ openio_conscience_serviceid }}-services.conf"
    - src: "policies.conf.j2"
      dest: "{{ openio_conscience_sysconfig_dir }}/\
        conscience-{{ openio_conscience_serviceid }}/conscience-{{ openio_conscience_serviceid }}-policies.conf"
    - src: "gridinit_conscience.conf.j2"
      dest: "{{ openio_conscience_gridinit_dir }}/{{ openio_conscience_gridinit_file_prefix }}\
        conscience-{{ openio_conscience_serviceid }}.conf"
  register: _conscience_conf

- name: restart conscience
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_conscience_namespace}}-conscience-{{openio_conscience_serviceid}}
  when: _conscience_conf.changed
  tags: configure

...
